### ISSUE TITLE
Jump to next input box once a single digit is entered 

### ISSUE THREAD

**Issue by Poseidon-Heir** [Poseidon-Heir/Gamebullsandcows#3]
The four of each input boxes takes more than one character or digit ,we want it to jump to the next input box once a single digit is entered to enhance the UX ,to  understand  :https://poseidon-heir.github.io/Gamebullsandcows/   ; Try the game 

1.Folk this repo 
2.Clone the repo 
3.Create a branch 
4.Write your code 
5. Commit your changes
6. push the code 
7. compare and open pull request
--> l will verify and merge your code

**Comment by anmol111pal** [comment]
Hey, i would like to work on this is issue.

**Comment by anmol111pal** [comment]
> Hey, i would like to work on this is issue.

Please assign this to me @Poseidon-Heir
